package com.behavnotea.providerenrollment.model;

public enum Name {
    GROUP_MEMBERSHIP_AGREEMENT,
    PROOF_OF_TAX_ID,
    BACKGROUND_SCREENING,
    CERT_REGISTERED_BEHAVIOR_TECHNICIANS,
    NON_INSTITUTIONAL_PROVIDER_AGREEMENT
}
